all:
  children:
    web:
      hosts:
        web-1:
          ansible_host: 111.88.248.97
          internal_ip: 10.132.0.11

    kafka:
      hosts:
        kafka-1:
          ansible_host: 111.88.252.180
          internal_ip: 10.132.0.20

    elk:
      hosts:
        elk-1:
          ansible_host: 111.88.246.93
          internal_ip: 10.132.0.30

    log_agents:
      children:
        web: {}
