all:
  children:
    patroni_cluster:
      hosts:
        patroni-1:
          ansible_host: <PATRONI_1_PUBLIC_IP>
          patroni_node_ip: 10.130.0.11
          etcd_name: etcd1
        patroni-2:
          ansible_host: <PATRONI_2_PUBLIC_IP>
          patroni_node_ip: 10.130.0.12
          etcd_name: etcd2
        patroni-3:
          ansible_host: <PATRONI_3_PUBLIC_IP>
          patroni_node_ip: 10.130.0.13
          etcd_name: etcd3
    haproxy:
      hosts:
        haproxy-1:
          ansible_host: <HAPROXY_PUBLIC_IP>
          haproxy_node_ip: 10.130.0.20
