---
- name: Install Filebeat
  apt:
    name: "filebeat={{ elk_version }}"
    state: present

- name: Deploy Filebeat configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0644"
  notify: restart filebeat

- name: Enable and start Filebeat
  systemd:
    name: filebeat
    state: started
    enabled: yes

- name: Wait for Filebeat to start sending data
  pause:
    seconds: 15
