all:
  vars:
    # All non-bastion hosts are reached through consul-server-1 via SSH ProxyJump
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o ProxyJump=ubuntu@{{ bastion_public_ip }}

  children:
    consul_servers:
      hosts:
        consul-server-1:
          ansible_host: 93.77.183.156   # fill from: terraform output bastion_public_ip
          consul_bind_addr: 10.132.0.11
          # bastion connects directly — no ProxyJump for itself
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

        consul-server-2:
          ansible_host: 10.132.0.12           # internal IP, reached via bastion
          consul_bind_addr: 10.132.0.12

        consul-server-3:
          ansible_host: 10.132.0.13
          consul_bind_addr: 10.132.0.13

    web_servers:
      hosts:
        web-1:
          ansible_host: 10.132.0.21
          consul_bind_addr: 10.132.0.21

        web-2:
          ansible_host: 10.132.0.22
          consul_bind_addr: 10.132.0.22
