all:
  children:
    elasticsearch:
      hosts:
        elastic-1:
          ansible_host: 93.77.177.201
          es_node_ip: 10.131.0.11
          es_node_name: elastic-1
        elastic-2:
          ansible_host: 178.154.241.43
          es_node_ip: 10.131.0.12
          es_node_name: elastic-2
        elastic-3:
          ansible_host: 89.169.134.11
          es_node_ip: 10.131.0.13
          es_node_name: elastic-3
    logstash:
      hosts:
        logstash-1:
          ansible_host: 62.84.114.142
          logstash_node_ip: 10.131.0.20
    # Filebeat targets — nodes from homework6 cluster
    filebeat_targets:
      hosts:
        patroni-1:
          ansible_host: 178.154.247.138
        patroni-2:
          ansible_host: 158.160.118.99
        patroni-3:
          ansible_host: 178.154.230.2
        haproxy-1:
          ansible_host: 178.154.224.155
