---
- name: Install Kibana
  apt:
    name: "kibana={{ es_version }}"
    state: present

- name: Deploy Kibana configuration
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0660'
  notify: Restart kibana

- name: Enable and start Kibana
  systemd:
    name: kibana
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for Kibana to start
  uri:
    url: "http://127.0.0.1:{{ kibana_port }}/api/status"
    method: GET
    status_code: [200]
  register: kibana_health
  retries: 30
  delay: 10
  until: kibana_health.status == 200
  changed_when: false
